create extension if not exists "pgcrypto";

create table if not exists prediction_sessions (
  id uuid primary key default gen_random_uuid(),
  source text not null default 'web' check (source in ('web', 'desktop', 'api')),
  ip_address inet,
  user_agent text,
  client_label text,
  notes text,
  metadata jsonb,
  created_at timestamptz not null default now(),
  closed_at timestamptz
);

create table if not exists prediction_windows (
  id bigint generated by default as identity primary key,
  session_id uuid references prediction_sessions(id) on delete cascade,
  predicted_device text not null,
  prediction_confidence double precision not null check (prediction_confidence between 0 and 1),
  ground_truth_device text,
  feature_vector jsonb not null,
  raw_events jsonb,
  model_version text,
  window_started_at timestamptz,
  window_duration_ms integer,
  latency_ms integer,
  created_at timestamptz not null default now()
);

create index if not exists prediction_windows_session_id_idx on prediction_windows(session_id);
create index if not exists prediction_windows_ground_truth_idx on prediction_windows(ground_truth_device);

create table if not exists prediction_feedback (
  id bigint generated by default as identity primary key,
  prediction_id bigint references prediction_windows(id) on delete cascade,
  user_label text,
  is_correct boolean,
  rating smallint check (rating between 1 and 5),
  comments text,
  created_at timestamptz not null default now()
);

create table if not exists upload_logs (
  id bigint generated by default as identity primary key,
  upload_type text not null,
  file_name text,
  created_at timestamptz not null default now()
);
